const CONSTANTS = {
    NO_FILMS_FOUND: 'No Films found',
    ERROR: 'Error occurred while fetching the data!',
    NETFLIX: 'netflixroulette',
    FIND: 'FIND YOUR MOVIE',
    SEARCH_BY: 'SEARCH BY',
    TITLE: 'TITLE',
    GENRE: 'GENRE',
    SEARCH: 'SEARCH',
    MOVIES_FOUND: 'movies found',
    RATING: 'RATING',
    RELEASE: 'RELEASE DATE',
    SORT: 'SORT BY',
    EDIT: 'Edit',
    DELETE: 'Delete',
    ADD_MOVIE: '+ADD MOVIE',
    RESET: 'RESET',
    SUBMIT: 'SUBMIT',
    ADD_MOVIE_TITLE: 'ADD MOVIE',
    EDIT_MOVIE_TITLE: 'EDIT MOVIE',
    RESULTS_FOR: 'RESULTS FOR',
    PLEASE_SEARCH: 'Welcome to Netflix, Please search for your movies',
    NOT_FOUND_404: '404 Not Found',
    baseURL: 'http://localhost:4000/movies',
    SAMPLE_MOVIE: {
        title: 'La La Land',
        tagline: "Here's to the fools who dream.",
        vote_average: 7.9,
        vote_count: 6782,
        release_date: '2016-12-29',
        poster_path:
            'https://image.tmdb.org/t/p/w500/ylXCdC106IKiarftHkcacasaAcb.jpg',
        overview:
            'Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.',
        budget: 30000000,
        revenue: 445435700,
        runtime: 128,
        genres: ['Comedy', 'Drama', 'Romance'],
    },
}

export default CONSTANTS
